export default {
    montserrat: {
      black: "Arial",
      blackItalic: "Arial",
      bold: "Arial",
      boldItalic: "Arial",
      extraBold: "Arial",
      extraBoldItalic: "Arial",
      extraLight: "Arial",
      extraLightItalic: "Arial",
      italic: "Arial",
      light: "Arial",
      lightItalic: "Arial",
      medium: "Arial",
      mediumItalic: "Arial",
      regular: "Arial",
      semiBold: "Arial",
      semiBoldItalic: "Arial",
      thin: "Arial",
      thinItalic: "Arial",
    },
  };